#CREATE DATABASE survival;

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

/*
 * Session data stored in RAM.
 */
DROP TABLE IF EXISTS sessions;
CREATE TABLE sessions (
	sessionId VARCHAR(40) NOT NULL,
	sessionKey VARCHAR(40) NOT NULL,
	sessionData VARCHAR(255) NOT NULL default '',
	userId INT UNSIGNED NOT NULL,
	expires TIMESTAMP NOT NULL,
	PRIMARY KEY (sessionId),
	KEY userId (userId)
) ENGINE=MEMORY;

/*
 * Usage statistics, stored and updated in RAM.
 */
DROP TABLE IF EXISTS statistics_mem;
CREATE TABLE statistics_mem (
	id INT(10) UNSIGNED NOT NULL,
	userCount INT unsigned NOT NULL default 0,
	activeCount INT unsigned NOT NULL default 0,
	itemCount INT unsigned NOT NULl default 0,
	mobileCount INT unsigned NOT NULL default 0,
	PRIMARY KEY (id)
) ENGINE=MEMORY;

/*DROP TABLE IF EXISTS statistics;
CREATE TABLE statistics (
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
*/

DROP TABLE IF EXISTS leaderboard;
CREATE TABLE leaderboard (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,

	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS world;
CREATE TABLE world (
	id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,

	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*
 * User credentials, and avatar ID.
 */
DROP TABLE IF EXISTS users;
CREATE TABLE users (
	userId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	userName VARCHAR(40) NOT NULL,
	password VARCHAR(40) NOT NULL,
	firstName VARCHAR(40) NOT NULL DEFAULT '',
	lastName VARCHAR(40) NOT NULL DEFAULT '',
	playerId INT UNSIGNED NOT NULL,
	PRIMARY KEY (userId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

/*
 * Basic world object. Both mobiles and items extend from this.
 */
DROP TABLE IF EXISTS entities;
CREATE TABLE entities (
	entityId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
	name VARCHAR(40) NOT NULL,
	description TEXT NOT NULL DEFAULT '',
	graphic VARCHAR(40) NOT NULL,
	visible BOOLEAN NOT NULL DEFAULT TRUE,
	x INT NOT NULL,
	y INT NOT NULL,
	z INT NOT NULL,
	mapId int UNSIGNED NOT NULL,
	#created DATETIME NOT NULL,
	ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (entityId),
	KEY mapId (mapId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS items;
CREATE TABLE items (
	itemId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	value INT NOT NULL,
	hardness INT NOT NULL,
	identified BOOLEAN NOT NULL default FALSE,
	ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (itemId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS containers;
CREATE TABLE containers (
	containerId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (containerId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS weapons;
CREATE TABLE weapons (
	weaponId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	itemId INT UNSIGNED NOT NULL,
	ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (weaponId),
	KEY entityId(itemId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS armors;
CREATE TABLE armors (
	armorId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	itemId INT UNSIGNED NOT NULL,
	ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (armorId),
	KEY entityId(itemId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS mobiles;
CREATE TABLE mobiles (
	mobileId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(40) NOT NULL,
	description TEXT NOT NULL DEFAULT '',
	radius INT NOT NULL,
	size INT NOT NULL,
	graphic VARCHAR(40) NOT NULL,
	hp INT NOT NULL DEFAULT 0,
	visible BOOLEAN NOT NULL DEFAULT TRUE,
	military BOOLEAN NOT NULL DEFAULT FALSE,
	height DECIMAL NOT NULL,
	weight DECIMAL NOT NULL,
	mapId int UNSIGNED NOT NULL,
	x INT NOT NULL,
	y INT NOT NULL,
	z INT NOT NULL,
	created DATETIME NOT NULL,
	ts timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (mobileId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS locations;
CREATE TABLE locations (
	locationId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	description TEXT NOT NULL default '',
	value INT UNSIGNED NOT NULL default 0,
	PRIMARY KEY (locationId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DROP TABLE IF EXISTS maps;
CREATE TABLE maps (
	mapId INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	worldId INT(10) UNSIGNED NOT NULL,
	data LONGTEXT NOT NULL,
	lightLevel INT NOT NULL DEFAULT -1,
	lightFilter INT NOT NULL DEFAULT 0,
	PRIMARY KEY (mapId),
	KEY worldId(worldId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;